#!/bin/bash
compiler=~/development/circuitpython/mpy-cross-3.x-windows.exe

cd songs
python3 ./convert_to_binary.py
cd ..

for f in *.py; do
    if [[ $f != code.py ]]; then
	echo "compiling: $f"
	$compiler $f
    fi
done
